### ISSUE TITLE
Module error running cartpole_mpc_qlearning

### ISSUE THREAD

**Issue by wenlzhang** [MPC-Based-Reinforcement-Learning/mpc4rl#21]
I tried to run this example, but I received the following errors:

```
python scripts/cartpole_mpc_qlearning.py
Traceback (most recent call last):
  File "/..../scripts/cartpole_mpc_qlearning.py", line 8, in <module>
    from rlmpc.gym.continuous_cartpole.environment import ContinuousCartPoleSwingUpEnv  # noqa: F401
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/.../rlmpc/gym/continuous_cartpole/environment.py", line 8, in <module>
    from gymnasium.experimental.vector import VectorEnv
ModuleNotFoundError: No module named 'gymnasium.experimental.vector'
```

**Comment by 20040116** [comment]
gymnasium.experimental.vector has been removed in gymnasium>=0.28.0, which was changed into gymnasium.vector

So, you can change "from gymnasium.experimental.vector import VectorEnv" to "from gymnasium.vector import VectorEnv"

But there still will be an error:

Traceback (most recent call last):
  File "/home/lmy/RL/mpc4rl/mpc4rl-main/scripts/cartpole_mpc_qlearning.py", line 233, in <module>
    status = mpc.q_update(
  File "/home/lmy/RL/mpc4rl/mpc4rl-main/rlmpc/mpc/common/mpc.py", line 85, in q_update
    self.nlp, _ = update_nlp(self.nlp, self.ocp_solver)
  File "/home/lmy/RL/mpc4rl/mpc4rl-main/rlmpc/mpc/nlp.py", line 1364, in update_nlp
    nlp.set(stage, "lam", ocp_solver.get(stage, "lam"))
  File "/home/lmy/RL/mpc4rl/mpc4rl-main/rlmpc/mpc/nlp.py", line 305, in set
    return self.set_lam(stage_, value_)
  File "/home/lmy/RL/mpc4rl/mpc4rl-main/rlmpc/mpc/nlp.py", line 359, in set_lam
    assert np.concatenate(list(temp_lam_dict.values())).shape[0] == value_.shape[0], "Lamda vector has wrong shape."
AssertionError: Lamda vector has wrong shape.
